haproxy:
  image: eeacms/haproxy
  links:
  - webapp
  ports:
  - "80:5000"
  - "1936:1936"
  environment:
  - SERVICE_NAMES=webapp
  - BACKENDS_PORT=8080
#  - LOGGING=10.0.0.22

webapp:
  image: eeacms/hello
  environment:
  - PORT=8080
