haproxy:
#image: eeacms/haproxy
  build: haproxy
  links:
  - webapp
  ports:
  - "80:5000"
  - "1936:1936"
  environment:
  - SERVICE_NAMES=webapp
  - BACKENDS_PORT=8080
  volumes:
  - /etc

webapp:
  image: eeacms/hello
  environment:
  - PORT=8080
